module CarrierRecruitmentsHelper

  def paper_to_deliver_options
    [
      "AL, Montgomery- Montgomery Advertiser",
      "AR, Mountain Home- The Baxter Bulletin",
      "AZ, Phoenix- Arizona Republic",
      "CA, Camarillo- Ventura County Star",
      "CA, Palm Springs- The Desert Sun",
      "CA, Redding- Redding Record Searchlight",
      "CA, Salinas- The Californian",
      "CA, Tulare- Tulare Advance-Register",
      "CA, Visalia- Visalia Times-Delta",
      "CO, Fort Collins- Fort Collins Coloradoan",
      "DE, Wilmington- The News Journal",
      "FL, Brevard- Florida Today",
      "FL, Fort Myers- The News-Press",
      "FL, Naples- Naples Daily News",
      "FL, Pensacola- Pensacola News Journal",
      "FL, Stuart- The Stuart News",
      "FL, Tallahassee- Tallahassee Democrat",
      "IA, Des Moines- Des Moines Register",
      "IA, Iowa City- Iowa City Press-Citizen",
      "IN, Evansville- Evansville Courier And Press",
      "IN, Indianapolis- The Indianapolis Star",
      "IN, Lafayette IN- The Journal And Courier",
      "IN, Muncie- The Star Press",
      "IN, Richmond- Richmond Palladium - Item",
      "KY, Louisville- The Courier-Journal",
      "LA, Alexandria- The Town Talk",
      "LA, Lafayette LA- The Daily Advertiser",
      "LA, Monroe- The News-Star",
      "LA, Opelousas- The Daily World",
      "LA, Shreveport- The Times",
      "MD, Salisbury- The Daily Times",
      "MI, Battle Creek- Battle Creek Enquirer",
      "MI, Detroit- Detroit Free Press",
      "MI, Detroit- Detroit News",
      "MI, Lansing- Lansing State Journal",
      "MI, Livingston- Daily Press & Argus",
      "MI, Port Huron- Times Herald",
      "MN, St Cloud- St Cloud Times",
      "MO, Springfield- News-Leader",
      "MS, Hattiesburg- Hattiesburg American",
      "MS, Jackson MS- Clarion Ledger",
      "MT, Great Falls- Great Falls Tribune",
      "NC, Asheville- Citizen-Times",
      "NJ, Asbury Park Press- Asbury Park Press",
      "NJ, Bridgewater- Courier News",
      "NJ, Cherry Hill- Courier-Post",
      "NJ, East Brunswick- Home News Tribune",
      "NJ, Morristown- Daily Record",
      "NJ, Vineland- The Daily Journal",
      "NM, Alamogordo- Alamogordo Daily News",
      "NM, Carlsbad- Carlsbad Current Argus",
      "NM, Farmington- Farmington Daily Times",
      "NM, Las Cruces- Las Cruces Sun News",
      "NM, Deming- Deming Headlight",
      "NM, Silver City- Silver City Sun News ",
      "NV, Reno- Reno Gazette-Journal",
      "NV, TucsonTNI- The Arizona Daily Star",
      "NY, Binghamton- Press & Sun-Bulletin",
      "NY, Elmira- Star Gazette",
      "NY, Ithaca- Ithaca Journal",
      "NY, Poughkeepsie- Poughkeepsie Journal",
      "NY, Rochester- Democrat & Chronicle",
      "NY, Westchester Suburban- The Journal News",
      "OH, Bucyrus- Bucyrus Telegraph-Forum",
      "OH, Chillicothe- Chillicothe Gazette",
      "OH, Cincinnati- The Cincinnati Enquirer",
      "OH, Coshocton- Coshocton Tribune",
      "OH, Fremont- The News-Messenger",
      "OH, Lancaster- Lancaster Eagle-Gazette",
      "OH, Mansfield- Mansfield News Journal",
      "OH, Marion OH- Marion Star",
      "OH, Newark- Newark Advocate",
      "OH, Port Clinton- The News-Herald",
      "OH, Zanesville- Zanesville Times Recorder",
      "OR, Salem- Statesman Journal",
      "PA, Chambersburg- Public Opinion",
      "PA, Hanover- The Evening Sun",
      "PA, Lebanon- Lebanon Daily News",
      "PA, York- York Daily Record",
      "SC, Anderson- The Anderson Independent-Mail",
      "SC, Greenville- The Greenville News",
      "SD, Sioux Falls- Argus Leader",
      "TN, Clarksville- The Leaf-Chronicle",
      "TN, Jackson TN- The Jackson Sun",
      "TN, Knoxville- TheKnoxvilleNews-Sentinel",
      "TN, Memphis- TheCommercialAppeal",
      "TN, Murfreesboro- The Daily News Journal",
      "TN, Nashville- The Tennessean",
      "TX, Abilene- The Abilene Reporter-News",
      "TX, Corpus Christi- Corpus Christi Caller Times",
      "TX, El Paso- El Paso Times",
      "TX, San Angelo- San Angelo Standard-Times",
      "TX, Wichita Falls- Times Record News",
      "UT, St George- The Spectrum",
      "USA TODAY, Georgia",
      "USA TODAY, Virginia",
      "USA TODAY, North Carolina",
      "USA TODAY, South Carolina",
      "USA TODAY, Tennessee",
      "USA TODAY, Alabama",
      "USA TODAY, Florida",
      "VA, Staunton- The News Leader",
      "VT, Burlington- The Burlington Free Press",
      "WA, Bremerton- Kitsap Sun",
      "WI, Appleton- The Post-Crescent",
      "WI, CWS- Central Wisc Sunday",
      "WI, FondDuLac- The Reporter",
      "WI, Green Bay- Press-Gazette",
      "WI, Manitowoc- Herald Times Reporter",
      "WI, Marshfield- Marshfield News Herald",
      "WI, Milwaukee- Milwaukee Journal Sentinel",
      "WI, Oshkosh- Oshkosh Northwestern",
      "WI, Sheboygan- The Sheboygan Press",
      "WI, Stevens Point- Stevens Point Journal",
      "WI, Wausau- Wausau Daily Herald",
      "WI, Wisconsin Rapids- Rapids Daily Tribune"
    ]
  end
end
